"use client";

import React, { useState } from "react";

// ─── Scenario Knowledge Base ─────────────────────────────────────────────────
export const SCENARIO_INTEL: Record<string, {
  title: string;
  icon: string;
  tagline: string;
  what_it_is: string;
  real_world: string;
  trigger_inputs: Array<{ param: string; normal: string; abnormal: string; unit: string; icon: string }>;
  danger_chain: string[];
  stabilization: Array<{ action: string; targets: string; color: string }>;
  normal_state: { fuel_temp: string; power: string; pressure: string; coolant: string };
  difficultyColor: string;
}> = {
  normal: {
    title: "Normal Operation",
    icon: "🔋",
    tagline: "Baseline steady-state reactor run at nominal power",
    what_it_is:
      "The reactor runs at its design operating point. All systems function normally. No faults, no disturbances. This is the baseline the AI learns to maintain — and the reference state all fault scenarios deviate from.",
    real_world: "Like a power plant running on a clear, calm Tuesday with full staffing and zero alarms.",
    trigger_inputs: [
      { param: "Fuel Temperature", normal: "900–960", abnormal: "—", unit: "K", icon: "🌡️" },
      { param: "Reactor Power", normal: "95–105", abnormal: "—", unit: "%", icon: "⚡" },
      { param: "System Pressure", normal: "9–11", abnormal: "—", unit: "bar", icon: "💨" },
      { param: "Coolant Flow", normal: "~8,000", abnormal: "—", unit: "kg/s", icon: "💧" },
    ],
    danger_chain: ["No fault chain — this is steady-state operation"],
    stabilization: [
      { action: "Hold control rods at midpoint", targets: "Power ≈ 100%", color: "#00ff88" },
      { action: "Maintain coolant flow nominal", targets: "Coolant Temp < 310K", color: "#00ff88" },
    ],
    normal_state: { fuel_temp: "900–960 K", power: "95–105%", pressure: "9–11 bar", coolant: "≤310 K" },
    difficultyColor: "#00ff88",
  },
  lofa: {
    title: "Loss of Flow Accident (LOFA)",
    icon: "🌊",
    tagline: "Coolant pump failure — heat can't escape the core",
    what_it_is:
      "A pump failure drastically reduces coolant circulation through the reactor core. Without adequate flow, heat generated by fission accumulates faster than it can be removed. Fuel temperature spikes rapidly toward the safety limit of 1100K — if not controlled, this leads to core damage.",
    real_world:
      "Like a car radiator fan stopping while the engine runs at full power — coolant temperature spikes until the engine overheats.",
    trigger_inputs: [
      { param: "Coolant Flow", normal: "~8,000", abnormal: "< 3,000", unit: "kg/s", icon: "💧" },
      { param: "Coolant Temp", normal: "280–310", abnormal: "> 340", unit: "K", icon: "🌡️" },
      { param: "Fuel Temp", normal: "900–960", abnormal: "> 1000", unit: "K", icon: "🔥" },
      { param: "Reactor Power", normal: "95–105", abnormal: "> 120 (rising)", unit: "%", icon: "⚡" },
    ],
    danger_chain: [
      "Pump trips → coolant flow drops 60–80%",
      "Heat removal capacity plummets",
      "Fuel temperature climbs rapidly (+20–50K/step)",
      "If unchecked → fuel damage at >1100K",
    ],
    stabilization: [
      { action: "Insert control rods aggressively", targets: "Reduce power below 80%", color: "#fb2c36" },
      { action: "Boost secondary coolant loop", targets: "Restore heat removal", color: "#00c4ff" },
      { action: "Monitor temp rate (must go negative)", targets: "Temp Rate < 0 K/s", color: "#fbbf24" },
    ],
    normal_state: { fuel_temp: "< 960 K", power: "75–90%", pressure: "9–12 bar", coolant: "< 320 K" },
    difficultyColor: "#ff6568",
  },
  rod_stuck: {
    title: "Rod Stuck Event",
    icon: "🔒",
    tagline: "Control rod jams — AI loses a primary reactivity tool",
    what_it_is:
      "One or more control rods fail to respond to command signals due to mechanical seizure or hydraulic failure. Since control rods are the primary mechanism to absorb neutrons and modulate reactor power, losing them forces the AI to rely entirely on coolant flow adjustment to maintain stability.",
    real_world:
      "Like a car where the accelerator pedal is stuck — you must use brakes (coolant) alone to control speed since the primary throttle is broken.",
    trigger_inputs: [
      { param: "Rod Response", normal: "Full ±1.0", abnormal: "Blocked (0 effect)", unit: "norm.", icon: "🔒" },
      { param: "Reactivity", normal: "Controlled", abnormal: "Uncontrolled drift", unit: "—", icon: "⚛️" },
      { param: "Power Rate", normal: "≈ 0", abnormal: "> ±0.05/s", unit: "/s", icon: "📈" },
      { param: "Fuel Temp", normal: "900–960", abnormal: "> 990 (drift)", unit: "K", icon: "🌡️" },
    ],
    danger_chain: [
      "Rod command sent → rod does not move",
      "Reactivity (neutron multiplication) drifts un-compensated",
      "Power creeps upward or downward uncontrolled",
      "Temperature follows — AI must compensate via coolant only",
    ],
    stabilization: [
      { action: "Maximize coolant flow to absorb heat", targets: "Compensate for lost rod control", color: "#00c4ff" },
      { action: "Issue emergency SCRAM if temp > 1050K", targets: "Hard shutdown if needed", color: "#fb2c36" },
      { action: "Watch power rate — must stay ≈ 0", targets: "Power Rate within ±0.02/s", color: "#fbbf24" },
    ],
    normal_state: { fuel_temp: "< 970 K", power: "90–110%", pressure: "9–12 bar", coolant: "< 315 K" },
    difficultyColor: "#ff9f43",
  },
  power_ramp: {
    title: "Power Ramp Disturbance",
    icon: "📈",
    tagline: "Sudden large load demand — reactor must scale rapidly",
    what_it_is:
      "An external grid demand spike forces the reactor to rapidly ramp power output by 20–40%. This sudden increase in fission rate drives a fast rise in both fuel temperature and system pressure. The AI must smoothly follow the ramp target while preventing temperature excursions above 1050K.",
    real_world:
      "Like a city suddenly turning on a million air conditioners simultaneously — the power station must ramp up production instantly without blowing a fuse.",
    trigger_inputs: [
      { param: "Power Target", normal: "100%", abnormal: "120–140% (sudden)", unit: "%", icon: "⚡" },
      { param: "Power Rate", normal: "≈ 0", abnormal: "> +0.1/s", unit: "/s", icon: "📈" },
      { param: "Fuel Temp Rate", normal: "≈ 0 K/s", abnormal: "> +10 K/s", unit: "K/s", icon: "🌡️" },
      { param: "Pressure", normal: "9–11 bar", abnormal: "> 13 bar", unit: "bar", icon: "💨" },
    ],
    danger_chain: [
      "Grid demand spikes → power setpoint jumps 20–40%",
      "AI begins withdrawing control rods to boost fission",
      "Fuel temperature rises fast with power",
      "Pressure climbs due to increased coolant heating",
      "Risk: pressure exceedance >13.5 bar or temp >1050K",
    ],
    stabilization: [
      { action: "Controlled rod withdrawal (measured)", targets: "Follow ramp without overshoot", color: "#9ca3af" },
      { action: "Pre-emptively increase coolant flow", targets: "Stay ahead of rising heat", color: "#00c4ff" },
      { action: "Cap power rate ≤ +0.08/step", targets: "Smooth ramp, no spikes", color: "#fbbf24" },
    ],
    normal_state: { fuel_temp: "< 1020 K", power: "120–130% (settled)", pressure: "< 13 bar", coolant: "< 330 K" },
    difficultyColor: "#fbbf24",
  },
  sensor_noise: {
    title: "Sensor Noise Fault",
    icon: "📡",
    tagline: "Instrument readings corrupted — AI must filter bad data",
    what_it_is:
      "Sensor instrumentation develops faults, injecting random noise and spurious spikes into temperature and power readings. The control system receives corrupted data and may over-react to false readings — inserting rods when the reactor is actually stable, or missing real temperature rises hidden in noise.",
    real_world:
      "Like a doctor whose thermometer randomly adds ±5°C — treatment decisions become unreliable because the measurement itself can't be trusted.",
    trigger_inputs: [
      { param: "Sensor Noise Level", normal: "< 0.1%", abnormal: "+ 3–8% random", unit: "σ", icon: "📡" },
      { param: "Temperature Reading", normal: "Smooth", abnormal: "Jittery ±20K spikes", unit: "K", icon: "🌡️" },
      { param: "Power Reading", normal: "Smooth", abnormal: "Random ±5% jumps", unit: "%", icon: "⚡" },
      { param: "Control Reaction", normal: "Proportional", abnormal: "Over-correction risk", unit: "—", icon: "🤖" },
    ],
    danger_chain: [
      "Sensor calibration fails → readings gain random noise",
      "AI sees false high-temp reading → inserts rods too much",
      "Real power drops below 80% due to over-correction",
      "OR: AI ignores noise → misses real temperature drift",
    ],
    stabilization: [
      { action: "Smooth (filter) sensor readings in AI policy", targets: "Reduce action variance", color: "#00ff88" },
      { action: "Use conservative control actions", targets: "Avoid over-correction", color: "#fbbf24" },
      { action: "Cross-check rate-of-change vs absolute value", targets: "Detect false alarms", color: "#9ca3af" },
    ],
    normal_state: { fuel_temp: "900–980 K", power: "88–112% (filtered)", pressure: "9–12 bar", coolant: "< 315 K" },
    difficultyColor: "#a78bfa",
  },
};

// ─── Component ────────────────────────────────────────────────────────────────
interface ScenarioIntelPanelProps {
  selectedScenario: string | null;
  isRunning: boolean;
  currentState?: {
    fuel_temp: number;
    power: number;
    pressure: number;
    coolant_temp: number;
  } | null;
}

export const ScenarioIntelPanel: React.FC<ScenarioIntelPanelProps> = ({
  selectedScenario,
  isRunning,
  currentState,
}) => {
  const [tab, setTab] = useState<"overview" | "inputs" | "response">("overview");

  if (!selectedScenario || !SCENARIO_INTEL[selectedScenario]) {
    return (
      <div
        className="rounded-xl p-4 text-center"
        style={{
          background: "rgba(5,15,31,0.6)",
          border: "1px solid rgba(0,255,136,0.08)",
        }}
      >
        <div className="text-3xl mb-2 opacity-30">📋</div>
        <p className="text-xs" style={{ color: "rgba(107,143,168,0.5)" }}>
          Select a scenario to see its intelligence briefing
        </p>
      </div>
    );
  }

  const intel = SCENARIO_INTEL[selectedScenario];

  const tabs = [
    { id: "overview", label: "What Is It?" },
    { id: "inputs", label: "Inputs & Triggers" },
    { id: "response", label: "Stabilization" },
  ] as const;

  return (
    <div
      className="rounded-xl overflow-hidden"
      style={{
        background: "rgba(3,10,22,0.95)",
        border: `1px solid ${intel.difficultyColor}25`,
        boxShadow: `0 0 20px ${intel.difficultyColor}08`,
      }}
    >
      {/* Header */}
      <div
        className="px-4 py-3 flex items-start gap-3"
        style={{
          background: `linear-gradient(135deg, ${intel.difficultyColor}12, transparent)`,
          borderBottom: `1px solid ${intel.difficultyColor}20`,
        }}
      >
        <span className="text-2xl flex-shrink-0">{intel.icon}</span>
        <div className="min-w-0">
          <h3 className="text-sm font-bold leading-tight" style={{ color: "#e2f0ff" }}>
            {intel.title}
          </h3>
          <p className="text-xs mt-0.5" style={{ color: `${intel.difficultyColor}cc` }}>
            {intel.tagline}
          </p>
        </div>
        {isRunning && (
          <div
            className="flex-shrink-0 text-xs font-bold px-2 py-0.5 rounded-full animate-pulse"
            style={{
              background: `${intel.difficultyColor}20`,
              border: `1px solid ${intel.difficultyColor}50`,
              color: intel.difficultyColor,
            }}
          >
            LIVE
          </div>
        )}
      </div>

      {/* Tab Bar */}
      <div
        className="flex"
        style={{ borderBottom: "1px solid rgba(255,255,255,0.05)" }}
      >
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className="flex-1 py-2 text-xs font-semibold transition-all"
            style={{
              color: tab === t.id ? intel.difficultyColor : "rgba(107,143,168,0.5)",
              borderBottom: tab === t.id ? `2px solid ${intel.difficultyColor}` : "2px solid transparent",
              background: tab === t.id ? `${intel.difficultyColor}08` : "transparent",
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="p-4">
        {tab === "overview" && (
          <div className="space-y-3">
            <p className="text-xs leading-relaxed" style={{ color: "rgba(160,216,232,0.85)" }}>
              {intel.what_it_is}
            </p>
            <div
              className="rounded-lg p-3 text-xs leading-relaxed"
              style={{
                background: "rgba(0,0,0,0.3)",
                border: "1px solid rgba(255,255,255,0.04)",
                color: "rgba(107,143,168,0.7)",
              }}
            >
              <span style={{ color: "rgba(255,214,0,0.6)" }}>🌍 Real World Analogy: </span>
              {intel.real_world}
            </div>

            {/* Normal State Targets */}
            <div>
              <p className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: "rgba(107,143,168,0.5)" }}>
                Target Stable State
              </p>
              <div className="grid grid-cols-2 gap-1.5">
                {Object.entries(intel.normal_state).map(([key, val]) => (
                  <div
                    key={key}
                    className="rounded-lg px-2.5 py-1.5"
                    style={{ background: "rgba(0,255,136,0.05)", border: "1px solid rgba(0,255,136,0.12)" }}
                  >
                    <p className="text-xs uppercase" style={{ color: "rgba(107,143,168,0.5)", fontSize: "0.55rem" }}>
                      {key.replace("_", " ")}
                    </p>
                    <p className="font-mono font-bold text-xs" style={{ color: "#00ff88" }}>
                      {val}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {tab === "inputs" && (
          <div className="space-y-3">
            {/* Trigger Parameters Table */}
            <div>
              <p className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: "rgba(107,143,168,0.5)" }}>
                Parameters that cause this scenario
              </p>
              <div className="space-y-2">
                {intel.trigger_inputs.map((inp, i) => (
                  <div
                    key={i}
                    className="rounded-lg p-2.5"
                    style={{ background: "rgba(0,0,0,0.3)", border: "1px solid rgba(255,255,255,0.04)" }}
                  >
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-xs font-semibold" style={{ color: "#a0d8e8" }}>
                        {inp.icon} {inp.param}
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="flex-1">
                        <p className="text-xs" style={{ color: "rgba(107, 143, 168, 0.5)", fontSize: "0.55rem" }}>
                          NORMAL
                        </p>
                        <p className="font-mono text-xs font-bold" style={{ color: "#00ff88" }}>
                          {inp.normal} {inp.unit}
                        </p>
                      </div>
                      <div style={{ color: "rgba(107,143,168,0.3)", fontSize: "0.7rem" }}>→</div>
                      <div className="flex-1">
                        <p className="text-xs" style={{ color: "rgba(107, 143, 168, 0.5)", fontSize: "0.55rem" }}>
                          FAULT
                        </p>
                        <p
                          className="font-mono text-xs font-bold"
                          style={{ color: inp.abnormal === "—" ? "rgba(107,143,168,0.4)" : intel.difficultyColor }}
                        >
                          {inp.abnormal === "—" ? "Normal" : inp.abnormal + " " + inp.unit}
                        </p>
                      </div>

                      {/* Live value indicator */}
                      {currentState && isRunning && (
                        <div className="w-16 text-right">
                          <p className="text-xs" style={{ color: "rgba(107, 143, 168, 0.5)", fontSize: "0.55rem" }}>
                            LIVE
                          </p>
                          <p className="font-mono text-xs font-bold" style={{ color: "#fbbf24" }}>
                            {inp.param.toLowerCase().includes("fuel")
                              ? currentState.fuel_temp.toFixed(0)
                              : inp.param.toLowerCase().includes("power")
                              ? (currentState.power * 100).toFixed(0) + "%"
                              : inp.param.toLowerCase().includes("cool") && inp.unit === "K"
                              ? currentState.coolant_temp.toFixed(0)
                              : inp.param.toLowerCase().includes("press")
                              ? currentState.pressure.toFixed(1)
                              : "—"}
                            {" "}
                            {inp.param.toLowerCase().includes("power") ? "" : inp.unit !== "%" ? inp.unit : ""}
                          </p>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Danger Chain */}
            <div>
              <p className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: "rgba(107,143,168,0.5)" }}>
                ⚠️ Fault Escalation Chain
              </p>
              <div className="space-y-1">
                {intel.danger_chain.map((step, i) => (
                  <div key={i} className="flex items-start gap-2">
                    <div
                      className="flex-shrink-0 text-xs font-bold w-5 h-5 rounded-full flex items-center justify-center"
                      style={{
                        background: `${intel.difficultyColor}15`,
                        border: `1px solid ${intel.difficultyColor}40`,
                        color: intel.difficultyColor,
                        fontSize: "0.6rem",
                      }}
                    >
                      {i + 1}
                    </div>
                    <p className="text-xs leading-relaxed" style={{ color: "rgba(160,216,232,0.7)" }}>
                      {step}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {tab === "response" && (
          <div className="space-y-3">
            <p className="text-xs" style={{ color: "rgba(107,143,168,0.6)" }}>
              How the AI controller stabilizes this scenario:
            </p>

            {intel.stabilization.map((s, i) => (
              <div
                key={i}
                className="rounded-lg p-3"
                style={{
                  background: `${s.color}08`,
                  border: `1px solid ${s.color}25`,
                }}
              >
                <div className="flex items-start gap-2">
                  <div
                    className="flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold"
                    style={{ background: `${s.color}20`, color: s.color, border: `1px solid ${s.color}40` }}
                  >
                    {i + 1}
                  </div>
                  <div className="min-w-0">
                    <p className="text-xs font-semibold" style={{ color: "#e2f0ff" }}>
                      {s.action}
                    </p>
                    <p className="text-xs mt-0.5 font-mono" style={{ color: s.color }}>
                      → {s.targets}
                    </p>
                  </div>
                </div>
              </div>
            ))}

            <div
              className="rounded-lg p-3 text-xs"
              style={{
                background: "rgba(0,255,136,0.04)",
                border: "1px solid rgba(0,255,136,0.12)",
                color: "rgba(107,143,168,0.6)",
              }}
            >
              <span style={{ color: "rgba(0,255,136,0.7)" }}>✓ Success: </span>
              All parameters in normal range for 10+ consecutive steps = Stabilized
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ScenarioIntelPanel;
